# Assignment 1

### Q1 : Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.


In [1]:
name = "Akanksha Hotta"
print("Print my name :" + name)

Print my name :Akanksha Hotta


In [2]:
age = 20
age

20

### Q2 : X="Datascience is used to extract meaningful insights." Split the string

In [3]:
x = "Datascience is used to extract meaningful insights."
x1 = x.split()   #splitting a string

In [4]:
x1

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

### Q3 : Make a function that gives multiplication of two numbers. 

In [5]:
#creating a function with name Multiplication

def multiplication(a,b):
    c = a*b
    print(c)

In [6]:
multiplication(100,20.2)

2020.0


### Q4 : Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [7]:
dict = {"States": ["Gujrat","Goa","Maharastra","Jammu and Kashmir","Jharkhand"], "Capitals" : ["Gandhi_nagar","Panaji","Mumbai","Srinagar","Ranchi"]}
dict

{'States': ['Gujrat', 'Goa', 'Maharastra', 'Jammu and Kashmir', 'Jharkhand'],
 'Capitals': ['Gandhi_nagar', 'Panaji', 'Mumbai', 'Srinagar', 'Ranchi']}

In [8]:
dict.keys()

dict_keys(['States', 'Capitals'])

In [9]:
dict.values()

dict_values([['Gujrat', 'Goa', 'Maharastra', 'Jammu and Kashmir', 'Jharkhand'], ['Gandhi_nagar', 'Panaji', 'Mumbai', 'Srinagar', 'Ranchi']])

### Q5 : Create a list of 1000 numbers using range function.

In [10]:
#importing NumPy libraries
import numpy as np

In [11]:
np.arange(1000) #listing 1000 numbers means number from 0 till 999

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

### Q6 : Create an identity matrix of dimension 4 by 4

In [12]:
#with the help of EYE function

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Q7 : Create a 3x3 matrix with values ranging from 1 to 9.

In [13]:
#creating list
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matrix.ndim   #need to know dimension

2

### Q8 : Create 2 similar dimensional array and perform sum on them.

In [15]:
matrix1 = np.arange(1,10).reshape(3,3)
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
matrix2 = np.arange(10,19).reshape(3,3)
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [17]:
summation = matrix1 + matrix2
summation

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

### Q9 : Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [18]:
#import Pandas libraries

import pandas as pd

In [19]:
arr = [[],[],1,2,3,4,5],[6,7,8,9,10,11,12],[13,14,15,16,17,18,19],[20,21,22,23,24,25,26],[27,28,1]
df = pd.DataFrame(arr)
df

0   1   2     3     4     5     6
0  []  []   1   2.0   3.0   4.0   5.0
1   6   7   8   9.0  10.0  11.0  12.0
2  13  14  15  16.0  17.0  18.0  19.0
3  20  21  22  23.0  24.0  25.0  26.0
4  27  28   1   NaN   NaN   NaN   NaN

In [20]:
df = pd.DataFrame(arr,index=['1w','2w','3w','4w','5w'])
df

0   1   2     3     4     5     6
1w  []  []   1   2.0   3.0   4.0   5.0
2w   6   7   8   9.0  10.0  11.0  12.0
3w  13  14  15  16.0  17.0  18.0  19.0
4w  20  21  22  23.0  24.0  25.0  26.0
5w  27  28   1   NaN   NaN   NaN   NaN

In [21]:
df = pd.DataFrame(arr,columns=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'])
df

Mon Tue  Wed   Thu   Fri   Sat   Sun
0  []  []    1   2.0   3.0   4.0   5.0
1   6   7    8   9.0  10.0  11.0  12.0
2  13  14   15  16.0  17.0  18.0  19.0
3  20  21   22  23.0  24.0  25.0  26.0
4  27  28    1   NaN   NaN   NaN   NaN

In [22]:
df = pd.DataFrame(arr,index = ['1w','2w','3w','4w','5w'], columns=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'])
df

Mon Tue  Wed   Thu   Fri   Sat   Sun
1w  []  []    1   2.0   3.0   4.0   5.0
2w   6   7    8   9.0  10.0  11.0  12.0
3w  13  14   15  16.0  17.0  18.0  19.0
4w  20  21   22  23.0  24.0  25.0  26.0
5w  27  28    1   NaN   NaN   NaN   NaN

In [23]:
df['Thu'] = [2,9,16,23,'']
df

Mon Tue  Wed Thu   Fri   Sat   Sun
1w  []  []    1   2   3.0   4.0   5.0
2w   6   7    8   9  10.0  11.0  12.0
3w  13  14   15  16  17.0  18.0  19.0
4w  20  21   22  23  24.0  25.0  26.0
5w  27  28    1       NaN   NaN   NaN

In [24]:
df['Fri'] = [3,10,17,24,'']
df

Mon Tue  Wed Thu Fri   Sat   Sun
1w  []  []    1   2   3   4.0   5.0
2w   6   7    8   9  10  11.0  12.0
3w  13  14   15  16  17  18.0  19.0
4w  20  21   22  23  24  25.0  26.0
5w  27  28    1           NaN   NaN

In [25]:
df['Sat']=[4,11,18,25,'']
df

Mon Tue  Wed Thu Fri Sat   Sun
1w  []  []    1   2   3   4   5.0
2w   6   7    8   9  10  11  12.0
3w  13  14   15  16  17  18  19.0
4w  20  21   22  23  24  25  26.0
5w  27  28    1               NaN

In [26]:
df['Sun'] = [5,12,19,26,'']
df

Mon Tue  Wed Thu Fri Sat Sun
1w  []  []    1   2   3   4   5
2w   6   7    8   9  10  11  12
3w  13  14   15  16  17  18  19
4w  20  21   22  23  24  25  26
5w  27  28    1

In [27]:
df['Mon'] = ['',6,13,20,27]
df

Mon Tue  Wed Thu Fri Sat Sun
1w      []    1   2   3   4   5
2w   6   7    8   9  10  11  12
3w  13  14   15  16  17  18  19
4w  20  21   22  23  24  25  26
5w  27  28    1

In [28]:
df['Tue'] = ['', 7,14,21,28]
df

Mon Tue  Wed Thu Fri Sat Sun
1w            1   2   3   4   5
2w   6   7    8   9  10  11  12
3w  13  14   15  16  17  18  19
4w  20  21   22  23  24  25  26
5w  27  28    1

In [29]:
df                             #final output from feb 1st 2023 to 1st March 2023

Mon Tue  Wed Thu Fri Sat Sun
1w            1   2   3   4   5
2w   6   7    8   9  10  11  12
3w  13  14   15  16  17  18  19
4w  20  21   22  23  24  25  26
5w  27  28    1

### Q 10 : Given a dictionary, convert it into corresponding dataframe and display it dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]

In [30]:
#creating dictionary 

dict1 = {'Brand' : ["Maruti","Renault","Hyundai"],'Sales' : [250,200,240]}
dict1

{'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}

In [31]:
#creating DataFrame from Dictionary

df1 = pd.DataFrame(dict1)
df1

Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240

In [32]:
#renaming the index values

df1=pd.DataFrame(dict1,index=[1,2,3])
df1

Brand  Sales
1   Maruti    250
2  Renault    200
3  Hyundai    240